### ISSUE TITLE
text offset dont match face offset?

### ISSUE THREAD

**Issue by Elmapul** [brunosxs/SMRT-Godot#6] opened 2017-09-22 13:11 UTC
the text is under the face, due to different offsets.

**Comment by brunosxs** [comment] 2017-10-02 10:27
Well that's strange, it should match.
I am really busy with college(and will for months to come), but send an example project with the bug so that when I have the time I can look and see if it is a bug in SMRT.

**Comment by brunosxs** [comment] 2017-11-27 01:22
Since I can't reproduce the bug and I've got no answer, I'll close this issue.

**Closed as completed by brunosxs** 2017-11-27 01:22 UTC
